name: Create Pull Request on File Push

on:
  push:

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update specific file"
          title: "Update from specific file push"
          body: "This is an automated pull request triggered by an update to a specific file."
          branch: "updates-for-main"
          base: "main"
